#!/usr/bin/env python
import sys

from model import train
# from services.cloud import download, upload


if __name__ == '__main__':
    
    # file_path = str(constants.INPUT_PATH / 'train.zip')
    # download(file_path, 'input/train.zip')
    train()
    # file_path = str(constants.MODEL_PATH / "model.joblib")
    # upload(file_path, 'output/model.joblib')

    # A zero exit code causes the job to be marked a Succeeded.
    sys.exit(0)