#!/usr/bin/env python

import logging
import os
import sys
import time

import constants
from model import train
# from services.cloud import get_data, save_artifacts


if __name__ == '__main__':
  
    # file_path = constants.INPUT_PATH / 'train.zip'
    # get_data(file_path, 'input/train.zip')
    train()
    # file_path = constants.MODEL_PATH / "model.joblib"
    # save_artifacts(file_path, 'output/model.joblib')

    # A zero exit code causes the job to be marked a Succeeded.
    sys.exit(0)